### ISSUE TITLE
ReferenceError: Dynamsoft is not defined

### ISSUE THREAD

**Issue by dimalusa** [dynamsoft-dwt/react#1]
Hi,

When  try your project, i've got the following error :

```
WebTwain.js:15 Uncaught ReferenceError: Dynamsoft is not defined
    at WebTwain.handleClick (WebTwain.js:15)
    at Object.ReactErrorUtils.invokeGuardedCallback (
```

An idea ?

Thanks !

**Comment by dimalusa** [comment]
When I try the "same" code with vuejs, I've got the same error. :(

**Comment by dimalusa** [comment]
Sorry, stupid error....
Everything seems OK.
I "just have" to reproduce react-scripts with vuejs...

**Comment by yushulx** [comment]
@dimalusa can I close the issue now?

**Comment by dimalusa** [comment]
Yes you can !!! ;)
